// ============================================================
// FEMSTUDIO PM AUTOMATION — Google Apps Script
// Author: Built by Claude for John Adeniran
// Runs: Every Sunday at 6PM — pushes full week to Google Calendar
// Daily reminders: 7AM briefing + 7PM work block
// ============================================================

var CONFIG = {
  email: "john.f.adeniran@gmail.com",
  calendarName: "FemStudio Tasks",
  morningReminderHour: 7,
  eveningReminderHour: 19,
  weeklyRunDay: 0,
  weeklyRunHour: 18,
  timezone: "America/Chicago"
};

function getFemStudioCalendar() {
  var calendars = CalendarApp.getCalendarsByName(CONFIG.calendarName);
  if (calendars.length > 0) return calendars[0];
  return CalendarApp.createCalendar(CONFIG.calendarName, {
    color: CalendarApp.Color.GRAPE,
    summary: "FemStudio weekly tasks — auto-generated by PM automation"
  });
}

function getCurrentWeek() {
  var start = new Date("2026-05-18");
  var now = new Date();
  var diff = Math.floor((now - start) / (7 * 24 * 60 * 60 * 1000));
  return Math.max(1, diff + 1);
}

function getTasksForWeek(weekNum) {
  return weekNum <= 2 ? TASK_BANK.phase1 : TASK_BANK.phase2;
}

function getNextMonday() {
  var now = new Date();
  var day = now.getDay();
  var daysUntilMonday = (day === 0) ? 1 : (8 - day);
  var monday = new Date(now);
  monday.setDate(now.getDate() + daysUntilMonday);
  monday.setHours(0, 0, 0, 0);
  return monday;
}

function createTaskEvent(calendar, task, monday) {
  var taskDate = new Date(monday);
  taskDate.setDate(monday.getDate() + (task.day - 1));
  var startTime = new Date(taskDate);
  startTime.setHours(CONFIG.eveningReminderHour, 0, 0, 0);
  var endTime = new Date(startTime);
  endTime.setMinutes(startTime.getMinutes() + task.duration);
  calendar.createEvent(task.title, startTime, endTime, {
    description: task.desc + "\n\n⏱ Estimated time: " + task.duration + " min\n\n💡 Need help? Open Claude → FemStudio project → describe where you are stuck.",
    reminders: { minutesBefore: [30, 10] }
  });
}

function createMorningBriefings(calendar, monday) {
  for (var i = 0; i < 5; i++) {
    var briefingDate = new Date(monday);
    briefingDate.setDate(monday.getDate() + i);
    briefingDate.setHours(CONFIG.morningReminderHour, 0, 0, 0);
    var briefingEnd = new Date(briefingDate);
    briefingEnd.setMinutes(briefingDate.getMinutes() + 5);
    calendar.createEvent("FemStudio morning check-in", briefingDate, briefingEnd, {
      description: "Open Claude → FemStudio project → type: FemStudio briefing\n\nGet today's task. Know your focus. Start strong.\n\nTakes 2 minutes.",
      reminders: { minutesBefore: [0] }
    });
  }
}

function sendWeeklySummaryEmail(tasks, weekNum, monday) {
  var subject = "FemStudio — Week " + weekNum + " tasks are locked in";

  var dayNames = ["", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"];
  var phaseLabel = weekNum <= 2 ? "Phase 1 — Foundation" : "Phase 2 — Growth";

  var taskCards = "";
  var currentDay = 0;

  tasks.forEach(function(task) {
    if (task.day !== currentDay) {
      if (currentDay !== 0) taskCards += "</div>";
      currentDay = task.day;
      taskCards += '<div style="margin-bottom:10px;">';
      taskCards += '<div style="background:#0a1f19;color:#c9a227;padding:9px 16px;border-radius:6px 6px 0 0;font-size:10px;font-weight:600;letter-spacing:0.1em;text-transform:uppercase;font-family:Arial,sans-serif;">' + dayNames[task.day] + '</div>';
    }

    var mins = task.duration;
    var timeLabel = mins <= 15 ? mins + " min" : mins <= 30 ? mins + " min" : mins + " min";
    var timeIcon = mins <= 15 ? "&#9889;" : "&#128336;";

    taskCards += '<div style="background:#ffffff;border:1px solid #e8e8e8;border-top:none;padding:14px 16px;">';
    taskCards += '<table width="100%" cellpadding="0" cellspacing="0"><tr>';
    taskCards += '<td style="font-size:14px;font-weight:600;color:#0f2d24;line-height:1.4;font-family:Georgia,serif;">' + task.title.replace("FemStudio — ", "") + '</td>';
    taskCards += '<td align="right" style="font-size:11px;color:#888888;white-space:nowrap;padding-left:12px;font-family:Arial,sans-serif;">' + timeIcon + ' ' + timeLabel + '</td>';
    taskCards += '</tr></table>';
    taskCards += '<div style="font-size:12px;color:#555555;line-height:1.65;border-left:3px solid #c9a227;padding-left:10px;margin-top:8px;font-family:Arial,sans-serif;">' + task.desc + '</div>';
    taskCards += '</div>';
  });
  if (currentDay !== 0) taskCards += "</div>";

  var totalMins = 0;
  tasks.forEach(function(t) { totalMins += t.duration; });
  var totalHrs = Math.floor(totalMins / 60);
  var remainMins = totalMins % 60;
  var totalTimeStr = totalHrs > 0 ? totalHrs + "h " + remainMins + "m" : totalMins + "m";

  var html = '<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head>';
  html += '<body style="margin:0;padding:0;background:#f0ede4;font-family:Arial,sans-serif;">';
  html += '<div style="max-width:600px;margin:0 auto;padding:24px 16px;">';

  // Header
  html += '<div style="background:#0f2d24;border-radius:10px 10px 0 0;padding:32px 28px 28px;">';
  html += '<div style="font-size:10px;color:#c9a227;letter-spacing:0.14em;text-transform:uppercase;margin-bottom:10px;font-family:Arial,sans-serif;">Week ' + weekNum + ' &nbsp;·&nbsp; ' + phaseLabel + '</div>';
  html += '<div style="font-size:28px;font-weight:700;color:#fcfbf7;letter-spacing:-0.5px;margin-bottom:6px;font-family:Georgia,serif;">FemStudio</div>';
  html += '<div style="font-size:14px;color:rgba(252,251,247,0.6);font-family:Georgia,serif;font-style:italic;">Your weekly task brief is ready, John.</div>';
  html += '</div>';

  // Stats bar
  html += '<table width="100%" cellpadding="0" cellspacing="0" style="background:#c9a227;">';
  html += '<tr>';
  html += '<td align="center" style="padding:14px 8px;">';
  html += '<div style="font-size:22px;font-weight:700;color:#0f2d24;font-family:Georgia,serif;">' + tasks.length + '</div>';
  html += '<div style="font-size:9px;color:#0f2d24;text-transform:uppercase;letter-spacing:0.1em;font-family:Arial,sans-serif;opacity:0.8;">Tasks</div>';
  html += '</td>';
  html += '<td style="width:1px;background:rgba(15,45,36,0.2);"></td>';
  html += '<td align="center" style="padding:14px 8px;">';
  html += '<div style="font-size:22px;font-weight:700;color:#0f2d24;font-family:Georgia,serif;">5</div>';
  html += '<div style="font-size:9px;color:#0f2d24;text-transform:uppercase;letter-spacing:0.1em;font-family:Arial,sans-serif;opacity:0.8;">Days</div>';
  html += '</td>';
  html += '<td style="width:1px;background:rgba(15,45,36,0.2);"></td>';
  html += '<td align="center" style="padding:14px 8px;">';
  html += '<div style="font-size:22px;font-weight:700;color:#0f2d24;font-family:Georgia,serif;">' + totalTimeStr + '</div>';
  html += '<div style="font-size:9px;color:#0f2d24;text-transform:uppercase;letter-spacing:0.1em;font-family:Arial,sans-serif;opacity:0.8;">Total time</div>';
  html += '</td>';
  html += '</tr></table>';

  // Task cards
  html += '<div style="background:#f0ede4;padding:16px 0;">';
  html += taskCards;
  html += '</div>';

  // Daily rhythm
  html += '<div style="background:#ffffff;border-radius:0 0 10px 10px;padding:22px 28px;">';
  html += '<div style="font-size:9px;font-weight:600;color:#0f2d24;text-transform:uppercase;letter-spacing:0.1em;margin-bottom:14px;opacity:0.5;font-family:Arial,sans-serif;">Your daily rhythm</div>';
  html += '<table width="100%" cellpadding="0" cellspacing="0"><tr>';

  html += '<td align="center" style="padding:12px 6px;background:#fcfbf7;border-radius:8px;">';
  html += '<div style="font-size:20px;margin-bottom:5px;">&#9728;&#65039;</div>';
  html += '<div style="font-size:12px;font-weight:600;color:#0f2d24;font-family:Georgia,serif;">7:00 AM</div>';
  html += '<div style="font-size:10px;color:#888888;margin-top:2px;font-family:Arial,sans-serif;">Morning check-in</div>';
  html += '</td>';

  html += '<td width="8"></td>';

  html += '<td align="center" style="padding:12px 6px;background:#fcfbf7;border-radius:8px;">';
  html += '<div style="font-size:20px;margin-bottom:5px;">&#128736;</div>';
  html += '<div style="font-size:12px;font-weight:600;color:#0f2d24;font-family:Georgia,serif;">7:00 PM</div>';
  html += '<div style="font-size:10px;color:#888888;margin-top:2px;font-family:Arial,sans-serif;">Work block</div>';
  html += '</td>';

  html += '<td width="8"></td>';

  html += '<td align="center" style="padding:12px 6px;background:#fcfbf7;border-radius:8px;">';
  html += '<div style="font-size:20px;margin-bottom:5px;">&#127769;</div>';
  html += '<div style="font-size:12px;font-weight:600;color:#0f2d24;font-family:Georgia,serif;">9:30 PM</div>';
  html += '<div style="font-size:10px;color:#888888;margin-top:2px;font-family:Arial,sans-serif;">Close-out</div>';
  html += '</td>';

  html += '</tr></table>';

  // CTA
  html += '<div style="margin-top:20px;text-align:center;">';
  html += '<a href="https://claude.ai" style="display:inline-block;background:#0f2d24;color:#c9a227;text-decoration:none;padding:13px 30px;border-radius:50px;font-size:11px;font-weight:600;letter-spacing:0.08em;text-transform:uppercase;font-family:Arial,sans-serif;">Open Claude &rarr; FemStudio Project</a>';
  html += '</div>';

  html += '<div style="margin-top:18px;text-align:center;font-size:10px;color:#bbbbbb;font-family:Arial,sans-serif;">femsstudio.com &nbsp;·&nbsp; Auto-generated by FemStudio PM System</div>';
  html += '</div>';

  html += '</div></body></html>';

  GmailApp.sendEmail(CONFIG.email, subject, "", { htmlBody: html });
  Logger.log("Sent branded FemStudio email to " + CONFIG.email);
}

var TASK_BANK = {
  phase1: [
    { title: "FemStudio — Set up Google Search Console", desc: "Go to search.google.com/search-console → add femsstudio.com → verify via Cloudflare DNS → submit sitemap.xml", duration: 30, day: 1 },
    { title: "FemStudio — Fix homepage meta title", desc: "Open VS Code → update app/page.tsx metadata → title: FemStudio | Brand Photographer and Web Designer in Houston TX → push to Vercel", duration: 15, day: 1 },
    { title: "FemStudio — Create Google Business Profile", desc: "business.google.com → create profile → category: Photographer → Houston service area → upload 5 photos → keyword-rich description", duration: 60, day: 2 },
    { title: "FemStudio — Add JSON-LD LocalBusiness schema", desc: "Ask Claude Code to generate JSON-LD block → inject into layout.tsx → push to Vercel → validate at schema.org/validator", duration: 30, day: 2 },
    { title: "FemStudio — Install Google Analytics 4", desc: "Create GA4 property → get measurement ID → add gtag script to layout.tsx via next/script → verify data is flowing", duration: 30, day: 3 },
    { title: "FemStudio — Build custom 404 page", desc: "Create app/not-found.tsx → branded page with links back to home and photography → push to Vercel", duration: 15, day: 3 },
    { title: "FemStudio — Remove dead old URLs in Search Console", desc: "Remove /author/rwsolar /digital-marketing /services /contact-us from GSC URL removal tool", duration: 15, day: 4 },
    { title: "FemStudio — Optimize all page meta descriptions", desc: "Review all 7 pages → rewrite meta descriptions targeting Houston photography and web design keywords → push to Vercel", duration: 60, day: 4 },
    { title: "FemStudio — First Google Search Console check", desc: "Open GSC → check crawl errors → check coverage report → check sitemap indexing → note any issues", duration: 30, day: 5 },
    { title: "FemStudio — Weekly review and planning", desc: "Open Claude FemStudio project → type FemStudio weekly review → log completed tasks → get next week top 3 priorities", duration: 20, day: 5 }
  ],
  phase2: [
    { title: "FemStudio — Optimize Photography page for Houston SEO", desc: "Rewrite photography page copy → include: brand photographer Houston, headshot photographer Houston TX, Houston neighborhoods", duration: 60, day: 1 },
    { title: "FemStudio — Optimize Web Design page for Houston SEO", desc: "Rewrite web design page copy → include: web designer Houston, custom web design Houston TX, small business websites Houston", duration: 60, day: 2 },
    { title: "FemStudio — Reach out to 5 past clients for Google reviews", desc: "Text or DM 5 past headshot clients → ask for a Google review → include your direct GBP review link", duration: 45, day: 2 },
    { title: "FemStudio — Add service areas to Google Business Profile", desc: "Open GBP → add: Houston, Katy, Sugar Land, The Woodlands, Pearland, Bellaire → update business description", duration: 20, day: 3 },
    { title: "FemStudio — Upload 10 new photos to GBP", desc: "Upload 10 portfolio photos → include headshots and brand sessions → add captions with Houston keywords", duration: 30, day: 3 },
    { title: "FemStudio — Review first GA4 data report", desc: "Open GA4 → review top pages, traffic sources, time on page, contact form events → note what needs attention", duration: 20, day: 4 },
    { title: "FemStudio — Add Photographer schema to Photography page", desc: "Ask Claude Code to add Photographer and LocalBusiness schema to photography page → push to Vercel → validate", duration: 30, day: 4 },
    { title: "FemStudio — Research competitor backlinks", desc: "Use Ubersuggest free → check where top 3 Houston headshot photographers get backlinks → note directories to list on", duration: 45, day: 5 },
    { title: "FemStudio — Submit to 3 Houston business directories", desc: "Submit femsstudio.com to: Yelp Houston, Thumbtack, Bark.com → consistent name address phone across all", duration: 45, day: 5 },
    { title: "FemStudio — Weekly review and planning", desc: "Open Claude FemStudio project → type FemStudio weekly review → log completed → get next week top 3 priorities", duration: 20, day: 5 }
  ]
};

function pushWeeklyTasksToCalendar() {
  try {
    var calendar = getFemStudioCalendar();
    var weekNum = getCurrentWeek();
    var monday = getNextMonday();
    var tasks = getTasksForWeek(weekNum);
    tasks.forEach(function(task) { createTaskEvent(calendar, task, monday); });
    createMorningBriefings(calendar, monday);
    sendWeeklySummaryEmail(tasks, weekNum, monday);
    Logger.log("FemStudio PM — weekly push complete. Week: " + weekNum);
  } catch(e) {
    Logger.log("Error: " + e.toString());
    GmailApp.sendEmail(CONFIG.email, "FemStudio PM — Script Error", "Something went wrong: " + e.toString());
  }
}

function testRun() {
  pushWeeklyTasksToCalendar();
  Logger.log("Test complete — check your Google Calendar and Gmail.");
}
