// ============================================================
// FEMSTUDIO PM AUTOMATION — Google Apps Script
// Author: Built by Claude for John Adeniran
// Runs: Every Sunday at 6PM — pushes full week to Google Calendar
// Daily reminders: 7AM briefing + 7PM work block
// ============================================================

var CONFIG = {
  email: "john.f.adeniran@gmail.com",
  calendarName: "FemStudio Tasks",
  morningReminderHour: 7,
  eveningReminderHour: 19,
  weeklyRunDay: 0,
  weeklyRunHour: 18,
  timezone: "America/Chicago"
};

function getFemStudioCalendar() {
  var calendars = CalendarApp.getCalendarsByName(CONFIG.calendarName);
  if (calendars.length > 0) return calendars[0];
  return CalendarApp.createCalendar(CONFIG.calendarName, {
    color: CalendarApp.Color.GRAPE,
    summary: "FemStudio weekly tasks — auto-generated by PM automation"
  });
}

function getCurrentWeek() {
  var start = new Date("2026-05-18");
  var now = new Date();
  var diff = Math.floor((now - start) / (7 * 24 * 60 * 60 * 1000));
  return Math.max(1, diff + 1);
}

function getTasksForWeek(weekNum) {
  return weekNum <= 2 ? TASK_BANK.phase1 : TASK_BANK.phase2;
}

function getNextMonday() {
  var now = new Date();
  var day = now.getDay();
  var daysUntilMonday = (day === 0) ? 1 : (8 - day);
  var monday = new Date(now);
  monday.setDate(now.getDate() + daysUntilMonday);
  monday.setHours(0, 0, 0, 0);
  return monday;
}

function createTaskEvent(calendar, task, monday) {
  var taskDate = new Date(monday);
  taskDate.setDate(monday.getDate() + (task.day - 1));
  var startTime = new Date(taskDate);
  startTime.setHours(CONFIG.eveningReminderHour, 0, 0, 0);
  var endTime = new Date(startTime);
  endTime.setMinutes(startTime.getMinutes() + task.duration);
  calendar.createEvent(task.title, startTime, endTime, {
    description: task.desc + "\n\n⏱ Estimated time: " + task.duration + " min\n\n💡 Need help? Open Claude → FemStudio project → describe where you are stuck.",
    reminders: { minutesBefore: [30, 10] }
  });
}

function createMorningBriefings(calendar, monday) {
  for (var i = 0; i < 5; i++) {
    var briefingDate = new Date(monday);
    briefingDate.setDate(monday.getDate() + i);
    briefingDate.setHours(CONFIG.morningReminderHour, 0, 0, 0);
    var briefingEnd = new Date(briefingDate);
    briefingEnd.setMinutes(briefingDate.getMinutes() + 5);
    calendar.createEvent("FemStudio morning check-in", briefingDate, briefingEnd, {
      description: "Open Claude → FemStudio project → type: FemStudio briefing\n\nGet today's task. Know your focus. Start strong.\n\nTakes 2 minutes.",
      reminders: { minutesBefore: [0] }
    });
  }
}

function sendWeeklySummaryEmail(tasks, weekNum, monday) {
  var subject = "FemStudio — Your week " + weekNum + " tasks are ready";
  var body = "Hey John,\n\nYour FemStudio tasks for the week are now in your Google Calendar.\n\nWEEK " + weekNum + " FOCUS:\n\n";
  var dayNames = ["", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"];
  tasks.forEach(function(task) {
    body += dayNames[task.day] + " — " + task.title.replace("FemStudio — ", "") + "\n";
    body += "Time: " + task.duration + " min\n";
    body += task.desc.substring(0, 100) + "...\n\n";
  });
  body += "REMINDERS:\n7AM — Check your calendar, know today's task\n7PM — Open VS Code, work your block\n9:30PM — Log what you finished\n\nNeed help on any task? Open Claude → FemStudio project.\n\nLet's build.\n\n— Your FemStudio PM System";
  GmailApp.sendEmail(CONFIG.email, subject, body);
}

var TASK_BANK = {
  phase1: [
    { title: "FemStudio — Set up Google Search Console", desc: "Go to search.google.com/search-console → add femsstudio.com → verify via Cloudflare DNS → submit sitemap.xml", duration: 30, day: 1 },
    { title: "FemStudio — Fix homepage meta title", desc: "Open VS Code → update app/page.tsx metadata → title: FemStudio | Brand Photographer and Web Designer in Houston TX → push to Vercel", duration: 15, day: 1 },
    { title: "FemStudio — Create Google Business Profile", desc: "business.google.com → create profile → category: Photographer → Houston service area → upload 5 photos → keyword-rich description", duration: 60, day: 2 },
    { title: "FemStudio — Add JSON-LD LocalBusiness schema", desc: "Ask Claude Code to generate JSON-LD block → inject into layout.tsx → push to Vercel → validate at schema.org/validator", duration: 30, day: 2 },
    { title: "FemStudio — Install Google Analytics 4", desc: "Create GA4 property → get measurement ID → add gtag script to layout.tsx via next/script → verify data is flowing", duration: 30, day: 3 },
    { title: "FemStudio — Build custom 404 page", desc: "Create app/not-found.tsx → branded page with links back to home and photography → push to Vercel", duration: 15, day: 3 },
    { title: "FemStudio — Remove dead old URLs in Search Console", desc: "Remove /author/rwsolar /digital-marketing /services /contact-us from GSC URL removal tool", duration: 15, day: 4 },
    { title: "FemStudio — Optimize all page meta descriptions", desc: "Review all 7 pages → rewrite meta descriptions targeting Houston photography and web design keywords → push to Vercel", duration: 60, day: 4 },
    { title: "FemStudio — First Google Search Console check", desc: "Open GSC → check crawl errors → check coverage report → check sitemap indexing → note any issues", duration: 30, day: 5 },
    { title: "FemStudio — Weekly review and planning", desc: "Open Claude FemStudio project → type FemStudio weekly review → log completed tasks → get next week top 3 priorities", duration: 20, day: 5 }
  ],
  phase2: [
    { title: "FemStudio — Optimize Photography page for Houston SEO", desc: "Rewrite photography page copy → include: brand photographer Houston, headshot photographer Houston TX, Houston neighborhoods", duration: 60, day: 1 },
    { title: "FemStudio — Optimize Web Design page for Houston SEO", desc: "Rewrite web design page copy → include: web designer Houston, custom web design Houston TX, small business websites Houston", duration: 60, day: 2 },
    { title: "FemStudio — Reach out to 5 past clients for Google reviews", desc: "Text or DM 5 past headshot clients → ask for a Google review → include your direct GBP review link", duration: 45, day: 2 },
    { title: "FemStudio — Add service areas to Google Business Profile", desc: "Open GBP → add: Houston, Katy, Sugar Land, The Woodlands, Pearland, Bellaire → update business description", duration: 20, day: 3 },
    { title: "FemStudio — Upload 10 new photos to GBP", desc: "Upload 10 portfolio photos → include headshots and brand sessions → add captions with Houston keywords", duration: 30, day: 3 },
    { title: "FemStudio — Review first GA4 data report", desc: "Open GA4 → review top pages, traffic sources, time on page, contact form events → note what needs attention", duration: 20, day: 4 },
    { title: "FemStudio — Add Photographer schema to Photography page", desc: "Ask Claude Code to add Photographer and LocalBusiness schema to photography page → push to Vercel → validate", duration: 30, day: 4 },
    { title: "FemStudio — Research competitor backlinks", desc: "Use Ubersuggest free → check where top 3 Houston headshot photographers get backlinks → note directories to list on", duration: 45, day: 5 },
    { title: "FemStudio — Submit to 3 Houston business directories", desc: "Submit femsstudio.com to: Yelp Houston, Thumbtack, Bark.com → consistent name address phone across all", duration: 45, day: 5 },
    { title: "FemStudio — Weekly review and planning", desc: "Open Claude FemStudio project → type FemStudio weekly review → log completed → get next week top 3 priorities", duration: 20, day: 5 }
  ]
};

function pushWeeklyTasksToCalendar() {
  try {
    var calendar = getFemStudioCalendar();
    var weekNum = getCurrentWeek();
    var monday = getNextMonday();
    var tasks = getTasksForWeek(weekNum);
    tasks.forEach(function(task) { createTaskEvent(calendar, task, monday); });
    createMorningBriefings(calendar, monday);
    sendWeeklySummaryEmail(tasks, weekNum, monday);
    Logger.log("FemStudio PM — weekly push complete. Week: " + weekNum);
  } catch(e) {
    Logger.log("Error: " + e.toString());
    GmailApp.sendEmail(CONFIG.email, "FemStudio PM — Script Error", "Something went wrong: " + e.toString());
  }
}

function testRun() {
  pushWeeklyTasksToCalendar();
  Logger.log("Test complete — check your Google Calendar and Gmail.");
}
